// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TodoItem struct {
	ID          int     `json:"id"`
	Title       string  `json:"title"`
	Content     *string `json:"content"`
	Checked     bool    `json:"checked"`
	CreatedTime string  `json:"createdTime"`
	UpdatedTime *string `json:"updatedTime"`
	User        *User   `json:"user"`
}

type TodoItemInput struct {
	Title       string  `json:"title"`
	Content     *string `json:"content"`
	Checked     bool    `json:"checked"`
	CreatedTime string  `json:"createdTime"`
	UpdatedTime *string `json:"updatedTime"`
}

type User struct {
	ID          int     `json:"id"`
	Username    string  `json:"username"`
	Password    *string `json:"password"`
	CreatedTime string  `json:"createdTime"`
	Token       *string `json:"token"`
}
